[package]
name = "webkitten"
version = "0.1.0"
authors = ["Delisa Mason <iskanamagus@gmail.com>"]

[dependencies]
libc = "0.2.8"
hlua = "0.1.7"
gtk-sys     = "0.2.1"
gobject-sys = "0.2.1"
gio-sys     = "0.2.1"
glib-sys    = "0.2.1"
