[package]
name = "webkitten"
version = "0.1.0"
authors = ["Delisa Mason <iskanamagus@gmail.com>"]
build = "build.rs"

[[bin]]
doc = false
name = "webkitten"

[dependencies]
hlua = "0.1.7"
libc = "0.2.8"
toml = "0.1.28"
gtk-sys     = "0.2.1"
gobject-sys = "0.2.1"
glib-sys    = "0.2.1"
