[package]
name = "webkitten"
version = "0.1.0"
authors = ["Delisa Mason <iskanamagus@gmail.com>"]

[dependencies]
hlua    = "0.1.8"
toml    = "0.1.30"
getopts = "0.2"
log     = "0.3"
url     = "1.1.1"
