[package]
name = "webkitten-cocoa"
version = "0.1.0"
authors = ["Delisa Mason <iskanamagus@gmail.com>"]

[dependencies]
objc = "0.2.7"
block = "0.1.6"
lazy_static = "1.4.0"
libc = "0.2.66"
log = "0.4.8"
webkitten = { path = "../" }
macos = { path = "../macos" }
dirs = "2.0.2"
