[package]
name = "webkitten-cocoa"
version = "0.1.0"
authors = ["Delisa Mason <iskanamagus@gmail.com>"]

[dependencies]
objc = "0.2"
block = "0.1"
lazy_static = "0.2"
libc = "0.2"
log = "0.4.8"
webkitten = { path = "../" }
macos = { path = "../macos" }
dirs = "2.0.2"
