[package]
name = "webkitten-cocoa"
version = "0.1.0"
authors = ["Delisa Mason <iskanamagus@gmail.com>"]

[dependencies]
cocoa = "0.4"
objc = "0.2"
block = "0.1"
core-graphics = ">=0.2, <0.4"
lazy_static = "0.2"
webkitten = { path = "../" }
