[package]
name = "webkitten-gtk"
version = "0.1.0"
authors = ["Delisa Mason <iskanamagus@gmail.com>"]
build = "build.rs"

[dependencies]
libc        = "0.2.8"
gtk-sys     = "0.2.1"
gobject-sys = "0.2.1"
glib-sys    = "0.2.1"
